services:
  - type: web
    name: Bitcoin
    env: python
    buildCommand: "./build.sh"
    startCommand: cd Bitcoin && gunicorn Bitcoin.wsgi:application
    healthCheckPath: /
    envVars:
      - key: "django-insecure-866l@6llvqyk=7h$1q6_@&%z^@ho@jakx#mb7#0vrwohfvn%6!"
        generateValue: true
