databases:
  - name: Bitcoin
    databaseName: carefi_bitcoin_api_database
    user: carefi_bitcoin_api_database_user

services:
  - type: web
    name: Bitcoin
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Bitcoin
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
